name: Benchmark PR

on:
  pull_request:
    paths: ["projects/**"]
    types: [opened, reopened, edited, synchronize]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    name: Run benchmarks for pr
    if: "${{ contains(github.event.pull_request.labels.*.name, 'ci: benchmark') }}"
    runs-on: benchmarking-runner

    steps:
      - uses: actions/checkout@v4

      - name: Install Stable Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install nodejs packages
        run: npm i

      - name: Install Wrk
        run: sudo apt-get update && sudo apt-get install -y wrk

      - name: Run Benchmarks
        run: cargo run
